server:
  # 启动端口号
  port: 19001
  # 工程路径
#  servlet:
#    context-path: /workorder
  # Tomcat中Post请求Form的最大长度
  tomcat:
    max-http-form-post-size: -1
spring:
  data:
    neo4j:
      username: neo4j
      password: 1qaz@WSX
      uri: bolt://172.16.20.160:7687
# 日志配置
logging:
  level:
    com.zyhk: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
test:
  username: 12345678


